### ISSUE TITLE
Missing type of input

### ISSUE THREAD

**Issue by mgilangjanuar** [mgilangjanuar/chat-wa#1]
Please add `type=tel` in input field

**Comment by sandy9808** [comment]
i can do it

**Comment by sandy9808** [comment]
I don't understand it, can u please elaborate ?

**Comment by mgilangjanuar** [comment]
In `IonInput` there is should be a `type` props, here is the doc: https://ionicframework.com/docs/api/input

Just append that prop 😉

**Comment by sandy9808** [comment]
Is this fine ?
![image](https://user-images.githubusercontent.com/58395595/94981012-595f4000-054c-11eb-989f-ddde14b53493.png)

I am a noob, sorry if i am disturbing you.

**Comment by mgilangjanuar** [comment]
Yes, cool! 🎊
